Machine Learning Essentials : Lab 12 : Cross Validation 
    
Name: Gaurav Pendharkar
    
Registration No.: 20BAI1153

# Importing the required modules

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier

# Reading the dataset

In [2]:
df = pd.read_csv("./nasa.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4687 entries, 0 to 4686
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Neo Reference ID              4687 non-null   int64  
 1   Name                          4687 non-null   int64  
 2   Absolute Magnitude            4687 non-null   float64
 3   Est Dia in KM(min)            4687 non-null   float64
 4   Est Dia in KM(max)            4687 non-null   float64
 5   Est Dia in M(min)             4687 non-null   float64
 6   Est Dia in M(max)             4687 non-null   float64
 7   Est Dia in Miles(min)         4687 non-null   float64
 8   Est Dia in Miles(max)         4687 non-null   float64
 9   Est Dia in Feet(min)          4687 non-null   float64
 10  Est Dia in Feet(max)          4687 non-null   float64
 11  Close Approach Date           4687 non-null   object 
 12  Epoch Date Close Approach     4687 non-null   int64  
 13  Rel

In [4]:
df = df.drop(list(df.columns)[0:2]+['Equinox','Close Approach Date','Orbit Determination Date','Orbit ID','Orbiting Body'],axis=1)

# Decision Trees

In [5]:
clf = DecisionTreeClassifier()

## 5 Fold cross validation

In [6]:
score_lr=cross_val_score(clf, df.drop(["Hazardous"],axis=1), df["Hazardous"],cv=5)
print(score_lr)
print("Avg :",np.average(score_lr))

[0.61513859 0.98827292 0.99573106 0.99466382 0.99679829]
Avg : 0.9181209367099553


Here, we infer that the model is not performing well with one of the test train splits. Hence, the average accuracy of the model is reducing.

## 10 Fold cross validation

In [7]:
score_lr=cross_val_score(clf, df.drop(["Hazardous"],axis=1), df["Hazardous"],cv=10)
print(score_lr)
print("Avg :",np.average(score_lr))

[0.9978678  0.99147122 0.99147122 0.99360341 0.99573561 0.9978678
 0.99147122 0.9957265  1.         0.99786325]
Avg : 0.9953078016510851


From 10 Fold cross validation is seems that the model performs well on the generated test train splits.

# Neural Network

# With default parameters

In [8]:
mlp = MLPClassifier()

## 5 Fold cross validation

In [9]:
score_lr=cross_val_score(mlp, df.drop(["Hazardous"],axis=1), df["Hazardous"],cv=5)
print(score_lr)
print("Avg :",np.average(score_lr))

[0.83901919 0.83901919 0.83884739 0.83884739 0.83884739]
Avg : 0.8389161070694705


After 5 fold cross validation, we can observe that the performance of the model on the chosen splits of the dataset has not much variation in it.

## 10 Fold cross validation

In [10]:
score_lr=cross_val_score(mlp, df.drop(["Hazardous"],axis=1), df["Hazardous"],cv=10)
print(score_lr)
print("Avg :",np.average(score_lr))

[0.16204691 0.83795309 0.83795309 0.83795309 0.83795309 0.84008529
 0.84008529 0.83974359 0.83974359 0.83974359]
Avg : 0.7713260619977037


From 10-Fold cross validation, we can observe that for some train train splits the model is not performing well, hence we can try early_stopping. 

# With Early Stopping

In [11]:
mlp = MLPClassifier(early_stopping = True)

## 5 Fold Cross Validation

In [12]:
score_lr=cross_val_score(mlp, df.drop(["Hazardous"],axis=1), df["Hazardous"],cv=5)
print(score_lr)
print("Avg :",np.average(score_lr))

[0.83901919 0.83901919 0.83884739 0.83884739 0.83884739]
Avg : 0.8389161070694705


There is not much of variation is the accuracy with 5 fold validations

## 10 Fold Cross Validation

In [13]:
score_lr=cross_val_score(mlp, df.drop(["Hazardous"],axis=1), df["Hazardous"],cv=10)
print(score_lr)
print("Avg :",np.average(score_lr))

[0.83795309 0.83795309 0.83795309 0.83795309 0.83795309 0.84008529
 0.84008529 0.83974359 0.83974359 0.83974359]
Avg : 0.8389166803345907


In 10 fold cross validation, also there is not much variation in the results.

With respect to the obtained results, a decision tree model is giving better average accuracy in both folds however the multilayer perceptron is giving a much more stable accuracy for both the splits.